apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-final
  region: "us-east-1"
  version: "1.23"

availabilityZones: ["us-east-1a" ,"us-east-1b"]
iam:
  serviceRoleARN: arn:aws:iam::636276102612:role/LabRole
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
  iam:
    instanceRoleARN: arn:aws:iam::636276102612:role/LabRole