apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: employeeapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: employeeapp
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: employeeapp
    spec:
      containers:
        - name: mysql-pod
          image: 045104524585.dkr.ecr.us-east-1.amazonaws.com/db:v1.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: '100m'
              memory: '500Mi'
            limits:
              cpu: '200m'
              memory: '1Gi'
