apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-svc
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.appservice.port }}
      targetPort: {{ .Values.appservice.targetPort }}
  selector:
    {{- include "myapp.labels" . | nindent 4 }}
