{{- if .Values.shared.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-rolebinding
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: hpa-svc-acc
  namespace: {{ .Values.metadata.namespace }}
roleRef:
  kind: Role
  name: hpa-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
