{{- if .Values.shared.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpa-svc-acc
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
{{- end }}
