apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-cluster-wide
  namespace: flux-system
spec:
  interval: 15m
  path: "./clusters/my-cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
