apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mydb-secrettest
  namespace: project
spec:
  encryptedData:
    password: AgBiamTigEykSrdC43ARCnVzaOZDpy930Aydpr5xYh8pZf+MGukeOTOc2PxgIfRhdE/LAjopl4Qpb/PGKAheDrOhqXElc4+xiQap8PpdW7Ip36plWXhPPW0FR0Aoi81VLFJYmbOHv5mw3IPQ2AwlXTF0bmfhgFK/07YKf6KEAKvDr3bfqei22D6Jo4j+sB32Ju4Sat4fKeZh3/AGk1y6onOWRPr9ZPhO+q9ZsxPUbPL/yJ26H4Mh/jycXdjlfrMBRtHHHZwShuy8VsXxXYwOgdpQ6hCmFizkXibxy8+XarAB1Br8XkHnZ+sPSTHYB8/P8ijSjzIcGCY/knKx6kZ6/Cq3+9mWGz4pbOR81L0yHCHGDxHFR561s8xJEYSYY1hjag6LNtd5wahC2meto3Wv2Zx5aa2Q8ii/4O9x2QMoyLpna9uy7O0ySYo2irgE0OKIM67LqxozgHQp9yaUSY6F0Xk5y1plsbaTfS2z6A/uzicRUZfxqfpvyN14PmNGT1UIQ2in8rQNVmLwWTDLYB1LVTY0fdzIF2AD6Nb4uU9CxHyOtl6yCkIJHyUuuXvrgXTkn4Dd7VEOuPL6NCaXaf8FdoWNcibHccycoJMDvi7y7MIpSOCg0Ot3wmILw/CKIpwsMhJiPThnNtcojTCiwu6AuSsfPrJ5aE4MC+FPnm/mN+jm+SPlp1sk2TmwOQ59gt27dPnqr6GXyZfWbSV2gQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mydb-secrettest
      namespace: project

