apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: final
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: employeeapp
    app.kubernetes.io/version: v1
spec:
  ports:
    - port: 80
      targetPort: 81
  selector:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: employeeapp
    app.kubernetes.io/version: v1
