apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k8manifest
  namespace: flux-system
spec:
  interval: 10m
  path: "./k8manifest"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: project
