apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: final
  name: hpa-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
