apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-rolebinding
  namespace: final
subjects:
- kind: ServiceAccount
  name: clo835-service-account
  namespace: final
roleRef:
  kind: Role
  name: hpa-role
  apiGroup: rbac.authorization.k8s.io