apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mydb-secret
  namespace: testflux
spec:
  encryptedData:
    password: AgAPgHCC98L9Eo7WiHdLVmO8twY1gOkGUTbg/4KEbDWM4aT3yyUf8Eh/V7bC6tDylcBJklUsfJWYK+pnWBv/dU2hS262TIA+mWf/s+3EAPYwSYgTkBdQP4IOLED50oZ3xSUXdQoe5kG5glgOymI1XMA0+DTspjSMeJQvcmkdBQLdSoB8NeUpjj+4KqG3l0PibSt6KmtTeqoJyjgMXQNcTBNT6C7c8CEID64kczD6RwrSZopnaKCBaI7r27YXMslIV+VJ8ySGv8kGd6mA+xGUDUkSOn6HsiVhRTNGFiuAS7mTfmJ0JmJRqPnMJCv7Q3EbnE3UgiAsL6Pphep/UqiBvQEBCZ7iDGzbuIlfBUN1A95UbeGhrxzvuvZRLuzQKdpdAcLUuBtbLWFvrCdaMQBx8GPTcij6+znvNyetbS/kXDOD2Ql1+a2k/8W+4Sn8EZ/0euas5SNzc8kzsLzGCUuPyE+5D2o+X+3OCvFuuqBJyPZv/PBoA7sBWmEiU70b346BegI1pgU453BTKWRlMBAiX4Og4rgcho18xb9eMK1rGzxIVNgmEptVBKXUUe94jl/TklSvpK57LqfsxjlqHoezVy+qAdrO74v8mLG4QhatbI+HrsaLBnbX6JvvIr+e4gqJ/NcU2LNwKi7U5QABlHtLUjh+oo/CvpfEwsXcghY/isVj/W71lT91VfiNQwRyiSsJxkpumM3SabSmwttvRA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mydb-secret
      namespace: testflux

