apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: "ssh://git@github.com/160683231-myseneca/Group10_Project_CLO835.git"
  ref:
    branch: dev
  secretRef:
    name: flux-git-deploy
