apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/my-cluster/flux-system"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - kind: Deployment
      name: source-controller
      namespace: flux-system
    - kind: Deployment
      name: kustomize-controller
      namespace: flux-system
