apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-db-replicaset
  namespace: sqldb
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: employeeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: employeeapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: employeeapp
    spec:
      containers:
      - name: mysql-pod
        image: 636276102612.dkr.ecr.us-east-1.amazonaws.com/mysql_image
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mydb-secret
              key: password
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
