apiVersion: v1
kind: Pod
metadata:
  name: myapp-v1-pod
  namespace: webapp
spec:
  containers:
  - name: myapp-v1-pod
    image: 636276102612.dkr.ecr.us-east-1.amazonaws.com/app_image
    env:
    - name: DBHOST
      value: {{POD_IP}}
    - name: DBPWD
      valueFrom:
        secretKeyRef:
          name: mydb-secret
          key: password
    - name: VERSION
      value: "v1"
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
