apiVersion: v1
kind: Service
metadata:
  name: myapp-{{APP_VERSION}}-nodeport
  namespace: webapp
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: employeeapp
    app.kubernetes.io/instance: myapp-{{APP_VERSION}}
    app.kubernetes.io/version: {{APP_VERSION}}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{APP_CONTAINER}}
  selector:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: employeeapp
    app.kubernetes.io/instance: myapp-{{APP_VERSION}}
    app.kubernetes.io/version: {{APP_VERSION}}
