apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-{{APP_VERSION}}
  namespace: webapp
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: employeeapp
    app.kubernetes.io/instance: myapp-{{APP_VERSION}}
    app.kubernetes.io/version: {{APP_VERSION}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: employeeapp
      app.kubernetes.io/instance: myapp-{{APP_VERSION}}
      app.kubernetes.io/version: {{APP_VERSION}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: employeeapp
        app.kubernetes.io/instance: myapp-{{APP_VERSION}}
        app.kubernetes.io/version: {{APP_VERSION}}
    spec:
      containers:
      - name: myapp-{{APP_VERSION}}-pod
        image: 636276102612.dkr.ecr.us-east-1.amazonaws.com/app_image
        env:
        - name: DBHOST
          value: "mysql-svc.sqldb.svc.cluster.local"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mydb-secret
              key: password
        - name: VERSION
          value: {{APP_VERSION}}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
